### ISSUE TITLE
Can't manually force a merge, error - efile_driver_unavailable [JIRA: RIAK-2036]

### ISSUE THREAD

**Issue by binarytemple** [basho/bitcask#218] opened 2015-07-20 20:06 UTC
I try running the following snippet.

```
{ok,Dataroot} = application:get_env(bitcask,data_root).
[{Idx, bitcask:merge(filename:join(Dataroot,integer_to_list(Idx)))} || {Idx,_Pid} <- riak_core_vnode_manager:all_index_pid(riak_kv_vnode)].
```
But I receive the following *efile_driver_unavailable* error:

```
** exception error: no case clause matching {error,efile_driver_unavailable}
     in function  bitcask_fileops:data_file_tstamps/1 (src/bitcask_fileops.erl, line 257)
     in call from bitcask:list_data_files/3 (src/bitcask.erl, line 1344)
     in call from bitcask:readable_and_setuid_files/1 (src/bitcask.erl, line 1666)
     in call from bitcask:readable_files/1 (src/bitcask.erl, line 1655)
     in call from bitcask:merge/2 (src/bitcask.erl, line 556)
```
Meanwhile, there are frequent needs_merge info messages appearing in the log:
```
2015-07-20 21:05:34.581 [info] <0.1338.0> "./data/bitcask/913438523331814323877303020447676887284957839360" needs_merge: [{"./data/bitcask/913438523331814323877303020447676887284957839360/4.bitcask.data",[{fragmented,95},{dead_bytes,500868293}]}]
```
I had previously changed the merge settings like so:
```
application:set_env(bitcask, merge_window, never).
application:set_env(bitcask,frag_merge_trigger, 40).
application:set_env(bitcask,max_file_size, 536870912).
application:set_env(bitcask,dead_bytes_merge_trigger, 214748364).
application:set_env(bitcask,frag_threshold, 20).
application:set_env(bitcask,dead_bytes_threshold, 107374182).
application:set_env(bitcask, log_needs_merge, true).
```
And run the following, to add 100000 1MB objects:
```
for i in {0..100000} ; do curl -XPUT localhost:10018/buckets/baz2/keys/$i -d@/tmp/lsof.txt  ; done
```

And run this to delete them:
```
for i in {0..100000} ; do curl -XDELETE localhost:10018/buckets/baz2/keys/$i ; done
```

**Comment by slfritchie** [comment] 2015-07-21 02:50
Bryan, your error is frequently caused by a mismatch of Erlang/OTP versions. NIF code is quite sensitive to the runtime that it was compiled for.  Please use the exact same Erlang/OTP runtime as Riak uses and see if the error happens again.

**Comment by binarytemple** [comment] 2015-07-21 09:01
@slfritchie that's was from a `riak attach` so should be using the correct run-time. I'll try to diagnose further.

**Comment by binarytemple-bet365** [comment] 2016-09-29 16:39
Riak 2.0.7, works correctly:

```
(riak@xxxxxxxxxx)18> {ok,Dataroot} = application:get_env(bitcask,data_root).
```
```
{ok,"/var/lib/riak/bitcask"}
```
````
(riak@xxxxxxxxxx)19> [{Idx, bitcask:merge(filename:join(Dataroot,integer_to_list(Idx)))} ||
 {Idx,_Pid} <- riak_core_vnode_manager:all_index_pid(riak_kv_vnode)].
```
```
[{1027618338748291114361965898003636498195577569280,ok},
 {1324485858831130769622089379649131486563188867072,ok},....]
```
Please close this ticket.

**Comment by binarytemple-bet365** [comment] 2016-09-29 16:41
@nickelization ^

**Comment by nickelization** [comment] 2016-10-04 15:56
:thumbsup:

**Closed by nickelization** 2016-10-04 15:56 UTC
Labels: JIRA: To Do
